### ISSUE TITLE
Guidance on how to activate the reactive support on spring-data cosmo 3.0.0.M1

### ISSUE THREAD

**Issue by kweheliye** [Microsoft/spring-data-cosmosdb#297]
I'm having issues in activating the reactive support in this early Pre-release, want to use and try out   the Async functionalities. Unfortunately I was unable to find documentation or  instructions on how to use this pre-release. 

In mongoDB to activate the reactive support, we   use the @EnableReactiveMongoRepositories alongside with some infrastructure setup (AbstractReactiveMongoConfiguration)

Please can you guide me on how to set up and activate the reactive support on cosmodb **SQL-API**
After setting up I can call the `ReactiveCrudRepository`  or one your reactive interfaces `ReactiveMongoRepository`

`@Repository
public interface TReactiveRepository 
  extends ReactiveCrudRepository<T, String> { }`

**Comment by Incarnation-p-lee** [comment]
@kweheliye 
Actually, we have plan to enable reactive support for spring data cosmosdb that may leverage spring-data-kay package instead of spring-data-commons. But spring-data-kay need RxJava 2.x, and our sdk current only support RxJava 1.x.
So we are blocked by this depending on sdk RxJava upgrade.

**Comment by xscript** [comment]
Duplicate to #299 .
