### ISSUE TITLE
This starter doesn't support database-provisioned throughput

### ISSUE THREAD

**Issue by Matthew-Dong** [microsoft/spring-data-cosmosdb#319]
Before Cosmos DB throughput could only be set on collection level, now (starting in May 2018) we can provision throughput on database level. 

When that is done, your starter fails to build as its internal tests seem to assume they always can set the throughput and the partition key on collection, and fail with "partition key required" error, while in reality it just fails with throughput setting as it's already set in the database. 

The actual error you will see is: DocumentClientException Provisioned throughput collection should have a partition key

**Comment by siddhantg-cbre** [comment]
I was able to create a database with db provisioned throughput from the CLI, add collections to it, and then point the starter to the database to run queries. However when I try to create a new collection on it, the new collection doesn't share the throughput, but provisions it's own

**Comment by jhauray** [comment]
+1!

**Comment by kushagraThapar** [comment]
We are targeting this feature for our next semester.

**Comment by kushagraThapar** [comment]
Closing it here as this is being tracked in a separate repo.

**Comment by siddhantg-cbre** [comment]
@kushagraThapar can you point us to where it's being tracked?

**Comment by kushagraThapar** [comment]
@siddhantg-cbre - Definitely, here you go : https://github.com/Azure/azure-sdk-for-java/issues/12715

This spring-data-cosmosdb repo is being migrated / moved to a new repo : https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos/azure-spring-data-cosmosdb

While source code has been migrated successfully, sample code and integration tests are still under progress. Once this repo movement is complete, this repo will no longer be active. Hence I am tracking all these issues in the new repo, since new development will happen there. 
This repo will only support hotfixes.
