### ISSUE TITLE
While writing a query how to take care of fileds with _ in their name ?

### ISSUE THREAD

**Issue by anshul-dhyani** [microsoft/spring-data-cosmosdb#349]
We are planning to use spring-data-cosmosdb artifact for writing new queries we want to finally move away from native queries and use spring-data abstraction .
But for existing collections which already have property names in snake case (Like first_name instead of firstName) how can I use this library?
it does not support adding one extra _ as escape character, is there a way to deal with entities with _ in name ?

for example : 
schema in DB is : 
```
{
	"first_name": "XYZ",
	"last_name": "ABC",
	"address": [{
			"address_type": 1,
			"house_number": "123",
			"street_number": "456",
			"street_name": "PQR"
		},
		{
			"address_type": 2,
			"house_number": "987",
			"street_number": "654",
			"street_name": "STU"
		}
	]
}
```

and i want to query by lastname 
i'll define query like below : 

> findByLast_Name(String lastName);

but after noticing _ after Last it will be looking for property name "Last" which does not exist.

So to over come this somewhere in stackoverflow I found someone suggesting to put additional _ which makes it look like : 

> findByLast__Name(String lastName);

But this extra underscore does not behaves as a escape character .

How can I make it work for collections already having above kind of schema ?
It will be of great help if there is already some work around for this situation or if we can introduce escape character kind of thing.

**Comment by Incarnation-p-lee** [comment]
@anshul-dhyani 
I am afraid you may need to follow the naming convention of Java. As spring-data framework keeps underscore as reserved char, see:

[Because we treat the underscore character as a reserved character, we strongly advise following standard Java naming conventions (that is, not using underscores in property names but using camel case instead).](https://docs.spring.io/spring-data/commons/docs/current/reference/html/#repositories.query-methods.query-property-expressions)

**Comment by anshul-dhyani** [comment]
I know it is reserved keyword for spring data as it is used to break the string for proper property traversal.
But do we have any way to deal with the properties already named with _ in it ?
If not do we have any plan to support that ?

**Comment by Incarnation-p-lee** [comment]
@anshul-dhyani 
I think we can do something to bypass the spring-data internal rules to make `_` works well. But from the implementation and maintenance perspective, I may prefer not to do that workaround for following reasons:

* May need to learn the implementation of spring-data-commons, which means the workaround of this may depends on the implement details of spring-data. That may result in problems once they upgrade.
* The naming contains `_` is quite weird from java work, it is difficult to call it feature I think.

I suppose you may depends on Class with these name which is not under your control, but there is also some workaround from you side instead of sdk. You can share more information about this, so we can figure out a better solution for this issue.

**Comment by anshul-dhyani** [comment]
Hi @Incarnation-p-lee ,

You got it correct, the POJOs have _ in the property name instead of being proper camel case, and I can't change it for existing collections.
for example we have collections with properties named with underscores in them and they use native azure cosmosDB sdk so they can work with them easily.
I thought it is good to use something like spring data so that in case you want to change DB in future its without extra dev efforts and spring data provides nice way of writing queries.
But with underscores in existing collection properties is making it difficult to use spring data sdk.

If possible you can point me to the work arounds which can make it work with collections with properties having underscores.

**Comment by Incarnation-p-lee** [comment]
@anshul-dhyani 
Sorry for late reply, from you description, I think you may need something like adapter or proxy class. Which can delegate the query instead of the target class. For example:

```java

class Target {
    private String id_value;
    private String name_value;
}

class Adapter {
    private final Target target;
    public Adapter(Target target) {
         this.target = target;
         init();
    }

    private void init() {
         this.idValue = target.id_value;
         this.nameValue = target.name_value;
    }

    private String idValue;
    private String nameValue;
}
```

And then you can query by adapter class fields, but may need more memory up to a point.

**Comment by anshul-dhyani** [comment]
Thank you @Incarnation-p-lee ,

I doubt if it will work as already collections are created with the underscore signs and when we define query it tries to match with property names of entity and make query with those properties and if the resultant query is not having underscores then it wont be able to fetch from DB, but I'll give it a try anyway.

**Comment by Incarnation-p-lee** [comment]
@anshul-dhyani 
Np, any problem please feel free to contact us.

**Comment by kushagraThapar** [comment]
@anshul-dhyani - feel free to open this issue or open a new one if you are still facing problems.
