### ISSUE TITLE
Upgrading azure-documentdb version from 1.16.2 to latest 2.x

### ISSUE THREAD

**Issue by apescione** [microsoft/spring-data-cosmosdb#418]
Spring Data Cosmos 2.1.7 is using the older version of azure-documentdb (1.16.2), so we cannot use new features, and moreover we cannot use some libraries that needs 2.x version, like the latest documentdb-bulkexecutor.
Overriding the version of azured-documentdb to the latest, we could face some issues. 
Is there a way to check compatibility among these versions?

**Comment by kushagraThapar** [comment]
azure-documentdb has announced deprecation. It will be deprecated in Jan 2020. 

Spring-data cosmosdb is moving away from azure-documentdb. 
2.1.7 release introduced ReactiveCosmosReporitory based on cosmosdb v3 SDK and also uses cosmosdb v3 SDK  for implementation of DocumentDbRepository. 

Since the deprecation will happen in Jan 2020, we still plan to support it. 

I can update the version of azure-documentdb in spring release 2.1.2.2 if that works for you guys.

**Comment by kushagraThapar** [comment]
@apescione Good move, regarding BulkExecutor, as far as I know, there is one in .Net, but not in java. We are building BulkExecutor for Azure Cosmos V3, or probably V4. It will take some time, might be available in early - mid November. 

I will close this issue now.
