### ISSUE TITLE
Spring data cosmos 2.1.7 does not autogenerate Id from repository class field with @Id during save api in CosmosClient

### ISSUE THREAD

**Issue by amanganiello90** [microsoft/spring-data-cosmosdb#428]
Hi,
updating from 2.1.2 to 2.1.7 version, the repository class with Id field annotation, that now uses **CosmosClient** class,  does not autogenerate id more, but in the creation requires to specify an id value.
I investigated, and I noticed that spring data save method uses CosmosClient with createItem method. It calls the CosmosContainer (that has this method), using the async createDocument with the **disableAutomaticIdGeneration** to true.

**Comment by kushagraThapar** [comment]
@amanganiello90 , Cosmos DB SDK doesn't support automatic id generation in v3 APIs. So you have to provide the Id manually going forward.

**Comment by amanganiello90** [comment]
> 
> 
> @amanganiello90 , Cosmos DB SDK doesn't support automatic id generation in v3 APIs. So you have to provide the Id manually going forward.

Yes, but the AsyncDocumentClient has the option in order to allow it, so I open an issue to the related repository understanding the reason that **CosmosClient** has this disabled. Thanks

**Comment by kushagraThapar** [comment]
@amanganiello90 , The reason `CosmosClient` has this disabled is because the Cosmos Database backend doesn't support it now (it used to support earlier) and that's why `AsyncDocumentClient` still has the parameter, but CosmosClient passes it as true by default (to disable the automatic id generation). 
Cosmos DB Java SDKs v1 has been deprecated, and we spring-data-cosmosdb has moved to v3 completely. 
v2.2.0.M1 has complete support for V3 and removed `DocumentClient` support (CosmosDB v1 SDK).

**Comment by edusevdev** [comment]
Hi all,
After test a app which were using the version 2.1.6 of **azure-cosmosdb-spring-boot-starter**, i had to migrate to version 2.1.7 because with previous version it didnt work findById, showing the following error:

`PartitionKey value must be supplied for this operation.`

To solve this we just to update to version 2.1.7 but this version not support the automatically id generation, so I found this post.
Indeed, we havent a native way with this version to support automatically id generation, but this has an easy solution.
We can use **_java.util.UUID_** to set ID when we need generate a new ID, this will facilitate us a new ID with the same format as the one that would give us the version 2.1.6.
In this way, we can to emulate a automatic ID generation.

In my case was enought with add the next method in the mappers for solve this problem:
       
```
@Mapping(target = "id", expression = "java( generateId(src) )")
User dtoToDomain(UserDTO src);
UserDTO domainToDTO(User src);
	
default String generateId(UserDTO dto) {
	return dto.getId() != null ? dto.getId() : UUID.randomUUID().toString();
}
```

**Comment by kushagraThapar** [comment]
@amanganiello90 We can close this issue now, as Cosmos DB SDK is not supporting the autogenerate ID  because of following reason: https://github.com/Azure/azure-sdk-for-java/issues/5512#issuecomment-552797267

If in future, we do support it, it will be released in spring-data-cosmosdb.

**Comment by PushkarKanikicherla** [comment]
Is there any update on this feature or work around to avoid manual generation of Id in the code? We are looking for a feature where cosmos take care of it instead application code doing that.
