### ISSUE TITLE
Config flag to enable/disable autocreate Containers(Cosmos SQL API) if not exists

### ISSUE THREAD

**Issue by prasadanair** [microsoft/spring-data-cosmosdb#454]
We are currently using 2.1.7 and have plans to move to 2.1.8(short-term) and 2.2.x(long-term). We are looking for an ability to disable "Auto-create Containers" behaviour of Spring data for CosmosDB, so that clients that are created using resource tokens(instead of master keys) does not fail.

It will be great if this feature is available as part of 2.1.x as well as 2.2.x.

**Comment by kushagraThapar** [comment]
@prasadanair , I am implementing this feature in 2.1.8 right now, and just wanted to give you a heads up on my implementation.
 
I am thinking to include a Boolean field in the @Document annotation which gets specified on an entity class. So that for any entity, you can decide if you want to auto create the collections or not.
 
Other way would be to put a Boolean flag in the properties file, but that will limit the flag to the complete application, and will not provide specific entity collection create ability.
 
Let me know if this makes sense.

**Comment by prasadanair** [comment]
Kushagra,
Looks good to me.

Thanks
Prasad

**Comment by kushagraThapar** [comment]
@prasadanair This has been released in v2.1.9

Will also be released as part of v2.2.1.M2 / v2.2.1 in next few days.

**Comment by kushagraThapar** [comment]
This has been released in v2.2.1, closing this issue now.
