### ISSUE TITLE
Autoscalling using Spring-Data-CosmosDb

### ISSUE THREAD

**Issue by vermaaditya** [microsoft/spring-data-cosmosdb#545]
Hi All, 

As a part of the new set of features, cosmos db provides auto-scalling at the containers level. - https://docs.microsoft.com/en-us/azure/cosmos-db/provision-throughput-autoscale.

The same can be achieved using Portal as well as ARM Templates. For reference attaching a screenshot of the ARM Template which is picked up from the MSDN - https://docs.microsoft.com/en-us/azure/cosmos-db/manage-sql-with-resource-manager - 
![image](https://user-images.githubusercontent.com/20763984/86124610-1038c380-baf9-11ea-9dbc-e1e9f2671307.png)
*****************
![image](https://user-images.githubusercontent.com/20763984/86124632-175fd180-baf9-11ea-86e6-658509be8e31.png)

I am trying to do the similar thing with the help of Spring-Data-CosmosDb library as my entire of the application is using the similar thing - attaching a screenshot for reference - 

![image](https://user-images.githubusercontent.com/20763984/86124954-8806ee00-baf9-11ea-9525-44f56fa705d9.png)

I am not able to find any thing for auto-scalling, kindly suggest.

**Comment by kushagraThapar** [comment]
@vermaaditya - This is not supported for current spring-data-cosmosdb releases. 

But we are planning to support this in new release version that will come out soon.

**Comment by vermaaditya** [comment]
@kushagraThapar - can you please help me with the tentative time line for 3.x.x milestone (which you have tagged). I see current version being 2.3.x and my application is targeted to be deployed in another month or so.. which is why i am asking if i should wait or use ARM templates.

**Comment by kushagraThapar** [comment]
@vermaaditya - v3.x.x is currently in development. It will be based on new azure-cosmos V4 SDK: https://devblogs.microsoft.com/cosmosdb/java-sdk-v4-ga/

This repo is migrating to this new location -> https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos/azure-spring-data-cosmosdb

The first preview version is scheduled to be out before end of July with updated APIs. I will try to include this feature before end of July, since we already have this feature in azure-cosmos V4 Java SDK.

**Comment by kushagraThapar** [comment]
Closing it here as this is being tracked in a separate repo.
